module Constants
  ALLOWED_GENRES            = ENV['ALLOWED_GENRES'].split(',')
  MOVIE_SEARCH_API_ENDPOINT = ENV['MOVIE_SEARCH_API_ENDPOINT']
  MOVIE_INFO_API_ENDPOINT   = ENV['MOVIE_INFO_API_ENDPOINT']
  ARTIST_INFO_API_ENDPOINT  = ENV['ARTIST_INFO_API_ENDPOINT']
  RETRY_DELAY_INTERVAL      = ENV['RETRY_DELAY_INTERVAL'].to_i || 1
  NUMBER_OF_RETRIES         = ENV['NUMBER_OF_RETRIES'].to_i || 3
end
